Repository SUSE/doc-sle, pull requests merged in 2021-06, with the labels that each got.

#881 added dual boot problems bsc#1185274
  xml/troubleshooting.xml
Labels: bug

#896 info for upgrading with zypper dup added bsc#1183681
  xml/zypper_upgrade.xml
Labels: bug

#905 modified info about boot error bsc#1185274
  xml/troubleshooting.xml
Labels: bug

#841 Document the new backend element in the networking section
  xml/ay_networking.xml
Labels: SLE 15 SP4+ only, on hold: merge later

#844 AutoYaST: improve <ask-list> description
  xml/ay_ask_user_values.xml
Labels: SLE 15 SP4+ only

#891 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement
