Repository SUSE/doc-sle, pull requests merged in 2022-05, with the labels that each got.

#1195 SEO fixes of broken links SLE15SP1
  xml/security_preface.xml
  xml/storage_nvmeof.xml
  xml/vt_best_practices.xml
  xml/xm_vs_xl_links.xml
Labels: enhancement

#1194 SEO fixes of broken links SLE15SP0
  xml/storage_nvmeof.xml
  xml/vt_best_practices.xml
  xml/xm_vs_xl_links.xml
Labels: enhancement

#1189 SEO fixes of broken links SLE15SP2
  xml/security_ldap_active_directory_sync.xml
  xml/security_preface.xml
  xml/storage_nvmeof.xml
  xml/vt_best_practices.xml
  xml/xm_vs_xl_links.xml
Labels: enhancement

#1188 SEO fixes of broken links_SLE15SP3
  xml/art_virtualization-best-practices.xml
  xml/security_ldap_active_directory_sync.xml
  xml/storage_nfs.xml
  xml/storage_nvmeof.xml
  xml/xm_vs_xl_links.xml
Labels: enhancement

#1187 SEO fixes of broken links_SLE12SP3
  xml/net_nfs.xml
  xml/storage_nvmeof.xml
  xml/vt_best_practices.xml
Labels: enhancement

#1185 SEO fixes of broken links_SLE12SP4
  xml/storage_nvmeof.xml
  xml/vt_best_practices.xml
Labels: enhancement

#1184 SEO fixes of broken links_SLE12SP5
  xml/storage_nvmeof.xml
  xml/vt_best_practices.xml
  xml/xm_vs_xl_links.xml
Labels: enhancement

#1208 Jufa/gnome update screens
  images/src/png/desktop_app_menu_firefox.png
  images/src/png/evince.png
  images/src/png/evolution.png
  images/src/png/file_roller.png
  images/src/png/gnome_yelp_main.png
  images/src/png/nautilus.png
  images/src/png/oo-wizard-base.png
  images/src/png/seahorse_main.png
  xml/apps_firefox.xml
  xml/apps_librevarious.xml
  xml/gnome_crypto.xml
  xml/gnome_start.xml
  xml/gnome_use.xml
Labels: bug

#1211 Use suse2022-ns stylesheets for SLE (SLES, SLED, SLE Micro)
  DC-SLE-Micro-administration
  DC-SLE-Micro-all
  DC-SLE-Micro-autoyast
  DC-SLE-Micro-deployment
  DC-SLE-Micro-podman
  DC-SLE-Micro-security
  DC-SLE-Micro-upgrade
  DC-SLED-administration
  DC-SLED-all
  DC-SLED-deployment
  DC-SLED-gnome-user
  DC-SLED-html
  DC-SLED-installation
  DC-SLED-modules
  DC-SLED-security
  DC-SLED-tuning
  DC-SLED-upgrade
  DC-SLES-administration
  DC-SLES-all
  DC-SLES-amd-sev
  DC-SLES-autoyast
  DC-SLES-container
  DC-SLES-deployment
  DC-SLES-gnome-user
  DC-SLES-html
  DC-SLES-installation
  DC-SLES-minimal-vm
  DC-SLES-modules
  DC-SLES-nvidia-vgpu
  DC-SLES-raspberry-pi
  DC-SLES-rmt
  DC-SLES-security
  DC-SLES-storage
  DC-SLES-tuning
  DC-SLES-upgrade
  DC-SLES-virtualization
  DC-SLES-virtualization-best-practices
Labels: enhancement

#1216 SEO fix coolsolution link
  l10n/sles/ja-jp/xml/storage_iscsi.xml
Labels: enhancement

#1218 SEO fix DHCP link
  l10n/sles/de-de/xml/net_dhcp.xml
Labels: enhancement

#1217 SEO fixes for SLE 15 SP0
  l10n/sles/de-de/xml/net_dhcp.xml
Labels: bug

#1220 SEO fixes of broken links SLE12SP4_JP
  l10n/sles/ja-jp/xml/adm_support.xml
  l10n/sles/ja-jp/xml/net_dhcp.xml
  l10n/sles/ja-jp/xml/storage_filesystems.xml
  l10n/sles/ja-jp/xml/storage_nvmeof.xml
Labels: enhancement

#1219 SEO fixes for de in SLE15 SP1
  l10n/sles/de-de/xml/net_dhcp.xml
Labels: bug

#1222 SEO fixes of broken links SLE12SP4_ZH_TW
  l10n/sles/zh-tw/xml/net_dhcp.xml
  l10n/sles/zh-tw/xml/storage_filesystems.xml
  l10n/sles/zh-tw/xml/storage_iscsi.xml
  l10n/sles/zh-tw/xml/storage_nvmeof.xml
Labels: bug

#1221 SEO fixes of broken links SLE12SP4_CN
  l10n/sles/zh-cn/xml/net_dhcp.xml
  l10n/sles/zh-cn/xml/storage_filesystems.xml
  l10n/sles/zh-cn/xml/storage_iscsi.xml
  l10n/sles/zh-cn/xml/storage_nvmeof.xml
Labels: bug

#1230 Jufa/seo fix links 12 sp3
  l10n/sles/de-de/xml/net_nfs.xml
  l10n/sles/ja-jp/xml/net_dhcp.xml
  l10n/sles/ja-jp/xml/net_nfs.xml
  l10n/sles/ja-jp/xml/storage_filesystems.xml
  l10n/sles/ja-jp/xml/storage_iscsi.xml
  l10n/sles/zh-cn/xml/net_dhcp.xml
  l10n/sles/zh-cn/xml/storage_filesystems.xml
  l10n/sles/zh-cn/xml/storage_iscsi.xml
  l10n/sles/zh-tw/xml/net_dhcp.xml
  l10n/sles/zh-tw/xml/net_nfs.xml
  l10n/sles/zh-tw/xml/storage_filesystems.xml
  l10n/sles/zh-tw/xml/storage_iscsi.xml
Labels: bug

#1231 SEO fix links SLE 12 SP5 l10n
  l10n/sles/de-de/xml/net_nfs.xml
  l10n/sles/ja-jp/xml/net_nfs.xml
  l10n/sles/ja-jp/xml/storage_filesystems.xml
  l10n/sles/ja-jp/xml/storage_iscsi.xml
  l10n/sles/ja-jp/xml/storage_nvmeof.xml
  l10n/sles/zh-cn/xml/net_nfs.xml
  l10n/sles/zh-cn/xml/storage_filesystems.xml
  l10n/sles/zh-cn/xml/storage_iscsi.xml
  l10n/sles/zh-cn/xml/storage_nvmeof.xml
  l10n/sles/zh-tw/xml/net_nfs.xml
  l10n/sles/zh-tw/xml/storage_filesystems.xml
  l10n/sles/zh-tw/xml/storage_iscsi.xml
  l10n/sles/zh-tw/xml/storage_nvmeof.xml
Labels: bug

#1236 fix bug, add alt text SEO
  xml/adm_support.xml
  xml/apparmor_profiles_yast.xml
  xml/apparmor_support.xml
  xml/apps_librevarious.xml
  xml/art_installation-sleds.xml
  xml/backup.xml
  xml/containers-basics.xml
  xml/containers-support.xml
  xml/deployment_yast_installer.xml
  xml/gnome_accessibility.xml
  xml/gnome_crypto.xml
  xml/gnome_custom.xml
  xml/gnome_networking.xml
  xml/gnome_start.xml
  xml/gnome_use.xml
  xml/installation-opensuse.xml
  xml/klp.xml
  xml/libvirt_host.xml
  xml/libvirt_managing.xml
  xml/net_bonding.xml
  xml/network_scheme.xml
  xml/opensuse_update.xml
  xml/rmt_mirroring.xml
  xml/security_xca.xml
  xml/snapper.xml
  xml/storage_fcoe.xml
  xml/storage_filesystems.xml
  xml/storage_iscsi.xml
  xml/storage_isns.xml
  xml/storage_lvm.xml
  xml/storage_raid10.xml
  xml/storage_raidroot.xml
  xml/systemd.xml
  xml/updater_gnome.xml
  xml/vt_tools.xml
  xml/yast2_lang.xml
  xml/yast2_userman.xml
Labels: bug, enhancement

#1237 fix bsc#1174735
  xml/gnome_start.xml
Labels: bug
