Repository SUSE/doc-sle, pull requests merged in 2022-11, with the labels that each got.

#1390 Remove broken link to Microfocus
  xml/adm_support.xml
Labels: bug

#1395 Jhalackova fips
  xml/book_security_slemicro.xml
  xml/security_fips.xml
Labels: WIP

#1397 Update deployment_prep_zseries_requirements.xml
  xml/deployment_prep_zseries_requirements.xml
Labels: SLEDocDay
